# Generated by Django 5.2.17 on 2026-09-25 08:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_business_profile_fields'),
        ('workspaces', '0002_alter_membership_options_alter_workspace_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name': 'бизнес', 'verbose_name_plural': 'бизнесы'},
        ),
        migrations.AlterField(
            model_name='business',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата архивации'),
        ),
        migrations.AlterField(
            model_name='business',
            name='audience',
            field=models.TextField(blank=True, verbose_name='целевая аудитория'),
        ),
        migrations.AlterField(
            model_name='business',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='business',
            name='goals',
            field=models.TextField(blank=True, verbose_name='цели бизнеса'),
        ),
        migrations.AlterField(
            model_name='business',
            name='language',
            field=models.CharField(default='ru', max_length=10, verbose_name='язык'),
        ),
        migrations.AlterField(
            model_name='business',
            name='market',
            field=models.CharField(blank=True, max_length=80, verbose_name='рынок'),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(max_length=200, verbose_name='название бизнеса'),
        ),
        migrations.AlterField(
            model_name='business',
            name='niche',
            field=models.CharField(blank=True, max_length=200, verbose_name='ниша'),
        ),
        migrations.AlterField(
            model_name='business',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='публичный идентификатор'),
        ),
        migrations.AlterField(
            model_name='business',
            name='slug',
            field=models.SlugField(max_length=220, verbose_name='слаг'),
        ),
        migrations.AlterField(
            model_name='business',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Активный'), ('ARCHIVED', 'Архивный')], default='ACTIVE', max_length=16, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='business',
            name='subniche',
            field=models.CharField(blank=True, max_length=200, verbose_name='подниша'),
        ),
        migrations.AlterField(
            model_name='business',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='дата изменения'),
        ),
        migrations.AlterField(
            model_name='business',
            name='website',
            field=models.URLField(blank=True, verbose_name='сайт'),
        ),
        migrations.AlterField(
            model_name='business',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='workspaces.workspace', verbose_name='рабочее пространство'),
        ),
    ]
