# Generated by Django 5.2.17 on 2026-09-25 08:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='публичный идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('source_id', models.CharField(max_length=180, unique=True, verbose_name='идентификатор источника')),
                ('title', models.CharField(max_length=240, verbose_name='название документа')),
                ('source_path', models.CharField(max_length=500, verbose_name='путь к исходному файлу')),
                ('language', models.CharField(default='ru', max_length=12, verbose_name='язык')),
                ('scope', models.CharField(choices=[('global', 'Общая база знаний')], default='global', max_length=40, verbose_name='область применения')),
                ('source_checked', models.DateField(blank=True, null=True, verbose_name='дата проверки источника')),
                ('effective_until', models.DateField(blank=True, null=True, verbose_name='действует до')),
                ('source_links', models.JSONField(blank=True, default=list, verbose_name='ссылки на источники')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='метаданные документа')),
                ('content_hash', models.CharField(max_length=64, verbose_name='контрольная сумма содержимого')),
                ('status', models.CharField(choices=[('approved', 'Утверждён')], default='approved', max_length=24, verbose_name='статус')),
            ],
            options={
                'verbose_name': 'документ базы знаний',
                'verbose_name_plural': 'документы базы знаний',
                'ordering': ('source_id',),
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='публичный идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('ordinal', models.PositiveIntegerField(verbose_name='номер фрагмента')),
                ('heading', models.CharField(blank=True, max_length=240, verbose_name='раздел')),
                ('content', models.TextField(verbose_name='текст фрагмента')),
                ('embedding', models.JSONField(blank=True, default=list, verbose_name='векторное представление')),
                ('embedding_model', models.CharField(blank=True, max_length=80, verbose_name='модель эмбеддингов')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.knowledgedocument', verbose_name='документ')),
            ],
            options={
                'verbose_name': 'фрагмент базы знаний',
                'verbose_name_plural': 'фрагменты базы знаний',
                'ordering': ('document_id', 'ordinal'),
                'constraints': [models.UniqueConstraint(fields=('document', 'ordinal'), name='knowledge_chunk_document_ordinal_uniq')],
            },
        ),
    ]
