# Generated by Django 5.2.17 on 2026-09-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgedocument',
            name='indexer_version',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='версия индексатора'),
        ),
    ]
