# Generated by Django 5.2.17 on 2026-09-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("strategist", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimessage",
            name="completion_tokens",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="aimessage",
            name="model",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="aimessage",
            name="prompt_tokens",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="aimessage",
            name="provider",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="aimessage",
            name="total_tokens",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
