# Generated by Django 5.2.17 on 2026-09-25 08:50

import apps.strategist.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_alter_business_options_alter_business_archived_at_and_more'),
        ('strategist', '0003_conversation_sessions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiconversation',
            options={'verbose_name': 'сессия ИИ-стратега', 'verbose_name_plural': 'сессии ИИ-стратега'},
        ),
        migrations.AlterModelOptions(
            name='aimessage',
            options={'ordering': ('created_at',), 'verbose_name': 'сообщение ИИ-стратега', 'verbose_name_plural': 'сообщения ИИ-стратега'},
        ),
        migrations.AlterField(
            model_name='aiconversation',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to='businesses.business', verbose_name='бизнес'),
        ),
        migrations.AlterField(
            model_name='aiconversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='aiconversation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='создатель'),
        ),
        migrations.AlterField(
            model_name='aiconversation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активна'),
        ),
        migrations.AlterField(
            model_name='aiconversation',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='публичный идентификатор'),
        ),
        migrations.AlterField(
            model_name='aiconversation',
            name='slug',
            field=models.SlugField(default=apps.strategist.models.default_conversation_slug, editable=False, max_length=220, unique=True, verbose_name='слаг'),
        ),
        migrations.AlterField(
            model_name='aiconversation',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='название сессии'),
        ),
        migrations.AlterField(
            model_name='aiconversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='дата изменения'),
        ),
        migrations.AlterField(
            model_name='aimessage',
            name='completion_tokens',
            field=models.PositiveIntegerField(default=0, verbose_name='токены ответа'),
        ),
        migrations.AlterField(
            model_name='aimessage',
            name='content',
            field=models.TextField(verbose_name='сообщение'),
        ),
        migrations.AlterField(
            model_name='aimessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='strategist.aiconversation', verbose_name='сессия'),
        ),
        migrations.AlterField(
            model_name='aimessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='aimessage',
            name='model',
            field=models.CharField(blank=True, max_length=80, verbose_name='модель ИИ'),
        ),
        migrations.AlterField(
            model_name='aimessage',
            name='prompt_tokens',
            field=models.PositiveIntegerField(default=0, verbose_name='токены запроса'),
        ),
        migrations.AlterField(
            model_name='aimessage',
            name='provider',
            field=models.CharField(blank=True, max_length=32, verbose_name='провайдер ИИ'),
        ),
        migrations.AlterField(
            model_name='aimessage',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='публичный идентификатор'),
        ),
        migrations.AlterField(
            model_name='aimessage',
            name='role',
            field=models.CharField(choices=[('USER', 'Пользователь'), ('ASSISTANT', 'ИИ-стратег')], max_length=16, verbose_name='отправитель'),
        ),
        migrations.AlterField(
            model_name='aimessage',
            name='total_tokens',
            field=models.PositiveIntegerField(default=0, verbose_name='всего токенов'),
        ),
        migrations.AlterField(
            model_name='aimessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='дата изменения'),
        ),
    ]
