# Generated by Django 5.2.17 on 2026-10-06 05:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_alter_business_options_alter_business_archived_at_and_more'),
        ('strategist', '0006_wbimageanalysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='публичный идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('ACTIVE', 'Действует'), ('ARCHIVED', 'В архиве')], default='DRAFT', max_length=16, verbose_name='статус')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='дата архивации')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='businesses.business', verbose_name='бизнес')),
            ],
            options={
                'verbose_name': 'стратегия',
                'verbose_name_plural': 'стратегии',
            },
        ),
        migrations.CreateModel(
            name='StrategyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='публичный идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('number', models.PositiveIntegerField(verbose_name='номер версии')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('CONFIRMED', 'Подтверждена'), ('SUPERSEDED', 'Заменена'), ('REJECTED', 'Отклонена')], default='DRAFT', max_length=16, verbose_name='статус')),
                ('goals', models.JSONField(blank=True, default=list, verbose_name='цели')),
                ('priorities', models.JSONField(blank=True, default=list, verbose_name='приоритеты')),
                ('keyword_clusters', models.JSONField(blank=True, default=list, verbose_name='группы ключевых слов')),
                ('recommended_boards', models.JSONField(blank=True, default=list, verbose_name='рекомендуемые доски')),
                ('content_directions', models.JSONField(blank=True, default=list, verbose_name='контентные направления')),
                ('publishing_cadence', models.JSONField(blank=True, default=dict, verbose_name='частота публикаций')),
                ('seasonal_plans', models.JSONField(blank=True, default=list, verbose_name='сезонные планы')),
                ('exclusions', models.JSONField(blank=True, default=list, verbose_name='исключения пользователя')),
                ('rationale', models.JSONField(blank=True, default=list, verbose_name='основания')),
                ('hypotheses', models.JSONField(blank=True, default=list, verbose_name='гипотезы')),
                ('missing_data', models.JSONField(blank=True, default=list, verbose_name='недостающие данные')),
                ('sources', models.JSONField(blank=True, default=list, verbose_name='источники (manifest)')),
                ('change_note', models.CharField(blank=True, max_length=500, verbose_name='что изменено')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='дата подтверждения')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='подтвердил')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='создатель')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='strategist.strategy', verbose_name='стратегия')),
            ],
            options={
                'verbose_name': 'версия стратегии',
                'verbose_name_plural': 'версии стратегии',
                'ordering': ('strategy', 'number'),
            },
        ),
        migrations.AddField(
            model_name='strategy',
            name='active_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='strategist.strategyversion', verbose_name='действующая версия'),
        ),
        migrations.AddConstraint(
            model_name='strategyversion',
            constraint=models.UniqueConstraint(fields=('strategy', 'number'), name='unique_strategy_version_number'),
        ),
    ]
