# Generated by Django 5.2.17 on 2026-10-06 05:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_alter_business_options_alter_business_archived_at_and_more'),
        ('pinterest', '0002_pinterestaccount_deleted_at_and_more'),
        ('strategist', '0007_strategy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='публичный идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('kind', models.CharField(choices=[('NICHE_KEYWORDS', 'Ключевые слова ниши')], default='NICHE_KEYWORDS', max_length=24, verbose_name='тип')),
                ('seeds', models.JSONField(blank=True, default=list, verbose_name='поисковые корни')),
                ('region', models.CharField(blank=True, max_length=40, verbose_name='регион')),
                ('candidates', models.JSONField(blank=True, default=list, verbose_name='найденные фразы')),
                ('notices', models.JSONField(blank=True, default=list, verbose_name='замечания источников')),
                ('total_tokens', models.PositiveIntegerField(default=0, verbose_name='токены')),
                ('researched_at', models.DateTimeField(verbose_name='дата исследования')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pinterest.pinterestaccount', verbose_name='аккаунт Pinterest')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_snapshots', to='businesses.business', verbose_name='бизнес')),
            ],
            options={
                'verbose_name': 'снимок исследования',
                'verbose_name_plural': 'снимки исследований',
                'ordering': ('-researched_at',),
            },
        ),
        migrations.AddField(
            model_name='strategyversion',
            name='research_snapshots',
            field=models.ManyToManyField(blank=True, related_name='strategy_versions', to='strategist.researchsnapshot', verbose_name='снимки исследований'),
        ),
    ]
