# Generated by Django 5.2.17 on 2026-10-06 05:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_alter_business_options_alter_business_archived_at_and_more'),
        ('strategist', '0008_researchsnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='публичный идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('kind', models.CharField(choices=[('FACT', 'Факт'), ('DECISION', 'Решение')], max_length=16, verbose_name='тип')),
                ('text', models.CharField(max_length=300, verbose_name='содержание')),
                ('reason', models.CharField(blank=True, max_length=300, verbose_name='причина')),
                ('source_ref', models.CharField(max_length=80, verbose_name='источник')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_items', to='businesses.business', verbose_name='бизнес')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='подтвердил')),
            ],
            options={
                'verbose_name': 'запись памяти бизнеса',
                'verbose_name_plural': 'память бизнеса',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['business', 'kind'], name='memory_business_kind_idx')],
            },
        ),
    ]
