# Generated by Django 5.2.17 on 2026-10-06 05:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_alter_business_options_alter_business_archived_at_and_more'),
        ('strategist', '0009_businessmemory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='публичный идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('horizon_weeks', models.PositiveSmallIntegerField(default=4, verbose_name='горизонт, недель')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('CONFIRMED', 'Подтверждён'), ('SUPERSEDED', 'Заменён')], default='DRAFT', max_length=16, verbose_name='статус')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='дата подтверждения')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_plans', to='businesses.business', verbose_name='бизнес')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='подтвердил')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='создатель')),
                ('strategy_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_plans', to='strategist.strategyversion', verbose_name='версия стратегии')),
            ],
            options={
                'verbose_name': 'контент-план',
                'verbose_name_plural': 'контент-планы',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ContentPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='публичный идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('position', models.PositiveSmallIntegerField(verbose_name='порядок')),
                ('target_week', models.PositiveSmallIntegerField(verbose_name='неделя плана')),
                ('direction', models.CharField(max_length=300, verbose_name='контентное направление')),
                ('board', models.CharField(blank=True, max_length=300, verbose_name='доска')),
                ('keyword', models.CharField(blank=True, max_length=300, verbose_name='ключевая фраза')),
                ('search_intent', models.CharField(blank=True, max_length=120, verbose_name='поисковое намерение')),
                ('content_type', models.CharField(choices=[('PIN', 'Пин'), ('VIDEO', 'Видео-пин')], default='PIN', max_length=8, verbose_name='тип контента')),
                ('priority', models.PositiveSmallIntegerField(default=2, verbose_name='приоритет')),
                ('idea', models.CharField(max_length=300, verbose_name='идея')),
                ('status', models.CharField(choices=[('PLANNED', 'Запланирован')], default='PLANNED', max_length=16, verbose_name='статус')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='strategist.contentplan', verbose_name='план')),
            ],
            options={
                'verbose_name': 'пункт контент-плана',
                'verbose_name_plural': 'пункты контент-плана',
                'ordering': ('plan', 'position'),
                'constraints': [models.UniqueConstraint(fields=('plan', 'position'), name='unique_plan_item_position')],
            },
        ),
    ]
