# Generated by Django 5.2.17 on 2026-10-06 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategist', '0010_contentplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentplan',
            name='strategy_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='content_plans', to='strategist.strategyversion', verbose_name='версия стратегии'),
        ),
    ]
