# Generated by Django 5.2.17 on 2026-10-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategist', '0011_alter_contentplan_strategy_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchsnapshot',
            name='kind',
            field=models.CharField(choices=[('NICHE_KEYWORDS', 'Ключевые слова ниши'), ('COVERAGE', 'Охват собственного контента')], default='NICHE_KEYWORDS', max_length=24, verbose_name='тип'),
        ),
    ]
