# Generated by Django 5.2.17 on 2026-10-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategist', '0012_alter_researchsnapshot_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimessage',
            name='context_manifest',
            field=models.JSONField(blank=True, default=list, verbose_name='источники контекста (manifest)'),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='prompt_version',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='версия промпта'),
        ),
    ]
