# Generated by Django 5.2.17 on 2026-10-06 12:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_alter_business_options_alter_business_archived_at_and_more'),
        ('strategist', '0013_aimessage_provenance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='публичный идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('status', models.CharField(choices=[('IDEA', 'Идея'), ('GENERATING', 'Генерируется'), ('VALIDATING', 'Проверяется'), ('WAITING_APPROVAL', 'Ждёт одобрения'), ('APPROVED', 'Одобрен'), ('QUEUED', 'В очереди'), ('PUBLISHING', 'Отправляется'), ('PUBLISHED', 'Опубликован'), ('REJECTED', 'Отклонён'), ('REWORK', 'Требуется переделка'), ('FAILED', 'Ошибка')], default='IDEA', max_length=20, verbose_name='статус')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='дата архивации')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='businesses.business', verbose_name='бизнес')),
                ('plan_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pin', to='strategist.contentplanitem', verbose_name='пункт контент-плана')),
            ],
            options={
                'verbose_name': 'пин',
                'verbose_name_plural': 'пины',
            },
        ),
        migrations.CreateModel(
            name='PinVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='публичный идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('number', models.PositiveIntegerField(verbose_name='номер версии')),
                ('title', models.CharField(max_length=300, verbose_name='заголовок')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('alt_text', models.CharField(blank=True, max_length=500, verbose_name='альтернативный текст')),
                ('destination_url', models.URLField(blank=True, max_length=500, verbose_name='ссылка назначения')),
                ('keyword', models.CharField(blank=True, max_length=300, verbose_name='ключевая фраза')),
                ('board', models.CharField(blank=True, max_length=300, verbose_name='доска')),
                ('checks', models.JSONField(blank=True, default=list, verbose_name='результаты проверок')),
                ('verdict', models.CharField(choices=[('PASS', 'Проверки пройдены'), ('REVIEW', 'Нужна оценка человека'), ('BLOCK', 'Заблокирован проверкой')], max_length=8, verbose_name='вердикт')),
                ('open_checks', models.JSONField(blank=True, default=list, verbose_name='невыполненные проверки')),
                ('generation', models.JSONField(blank=True, default=dict, verbose_name='происхождение текста')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='создатель')),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='strategist.pin', verbose_name='пин')),
            ],
            options={
                'verbose_name': 'версия пина',
                'verbose_name_plural': 'версии пинов',
                'ordering': ('pin', 'number'),
            },
        ),
        migrations.AddField(
            model_name='pin',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='strategist.pinversion', verbose_name='текущая версия'),
        ),
        migrations.AddConstraint(
            model_name='pinversion',
            constraint=models.UniqueConstraint(fields=('pin', 'number'), name='unique_pin_version_number'),
        ),
    ]
