# Generated by Django 5.2.17 on 2026-10-06 13:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategist', '0014_pin_pinversion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='публичный идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('decision', models.CharField(choices=[('APPROVED', 'Одобрен'), ('REJECTED', 'Отклонён'), ('REWORK', 'На переделку')], max_length=10, verbose_name='решение')),
                ('decided_at', models.DateTimeField(verbose_name='дата решения')),
                ('channel', models.CharField(default='WEB', max_length=16, verbose_name='канал')),
                ('comment', models.CharField(blank=True, max_length=300, verbose_name='комментарий')),
                ('acknowledged_checks', models.JSONField(blank=True, default=list, verbose_name='замечания, с которыми ознакомлен')),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='решил')),
                ('pin_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='strategist.pinversion', verbose_name='версия пина')),
            ],
            options={
                'verbose_name': 'решение по пину',
                'verbose_name_plural': 'решения по пинам',
            },
        ),
    ]
