# Generated by Django 5.2.17 on 2026-10-06 13:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_alter_business_options_alter_business_archived_at_and_more'),
        ('strategist', '0015_approval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='публичный идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('kind', models.CharField(choices=[('PIN_GENERATION', 'Генерация пинов')], max_length=24, verbose_name='тип')),
                ('status', models.CharField(choices=[('PENDING', 'В очереди'), ('RUNNING', 'Выполняется'), ('WAITING_INPUT', 'Ждёт ответа'), ('COMPLETED', 'Готово'), ('FAILED', 'Ошибка'), ('CANCELLED', 'Отменена')], default='PENDING', max_length=16, verbose_name='статус')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='параметры')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='всего')),
                ('done', models.PositiveIntegerField(default=0, verbose_name='готово')),
                ('failed', models.PositiveIntegerField(default=0, verbose_name='с ошибкой')),
                ('notes', models.JSONField(blank=True, default=list, verbose_name='сообщения')),
                ('cancel_requested', models.BooleanField(default=False, verbose_name='запрошена отмена')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='начата')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='завершена')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_jobs', to='businesses.business', verbose_name='бизнес')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='создатель')),
            ],
            options={
                'verbose_name': 'фоновая задача ИИ',
                'verbose_name_plural': 'фоновые задачи ИИ',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='GenerationPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='публичный идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('values', models.JSONField(blank=True, default=dict, verbose_name='настройки')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generation_preset', to='businesses.business', verbose_name='бизнес')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='изменил')),
            ],
            options={
                'verbose_name': 'настройки генерации пинов',
                'verbose_name_plural': 'настройки генерации пинов',
            },
        ),
    ]
