# Generated by Django 5.2.17 on 2026-10-07 01:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategist', '0016_aijob_generationpreset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PinImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='публичный идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('data', models.BinaryField(verbose_name='данные изображения')),
                ('content_type', models.CharField(max_length=20, verbose_name='тип')),
                ('width', models.PositiveIntegerField(verbose_name='ширина')),
                ('height', models.PositiveIntegerField(verbose_name='высота')),
                ('size', models.PositiveIntegerField(verbose_name='размер, байт')),
                ('sha256', models.CharField(max_length=64, verbose_name='хеш')),
                ('pin_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='strategist.pinversion', verbose_name='версия пина')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='загрузил')),
            ],
            options={
                'verbose_name': 'изображение пина',
                'verbose_name_plural': 'изображения пинов',
            },
        ),
    ]
