# Generated by Django 5.2.17 on 2026-09-28 04:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0003_alter_business_options_alter_business_archived_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PinterestAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='публичный идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('pinterest_user_id', models.CharField(max_length=100, unique=True, verbose_name='ID Pinterest')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='имя пользователя Pinterest')),
                ('access_token_encrypted', models.TextField(verbose_name='зашифрованный access token')),
                ('refresh_token_encrypted', models.TextField(blank=True, verbose_name='зашифрованный refresh token')),
                ('access_token_expires_at', models.DateTimeField(verbose_name='срок access token')),
                ('refresh_token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='срок refresh token')),
                ('granted_scopes', models.JSONField(default=list, verbose_name='выданные разрешения')),
                ('status', models.CharField(choices=[('CONNECTED', 'Подключён'), ('REAUTH_REQUIRED', 'Требуется переподключение'), ('DISCONNECTED', 'Отключён')], db_index=True, default='CONNECTED', max_length=24)),
                ('last_refresh_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_auth_error', models.CharField(blank=True, max_length=200)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinterest_accounts', to='businesses.business', verbose_name='бизнес')),
                ('connected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='connected_pinterest_accounts', to=settings.AUTH_USER_MODEL, verbose_name='подключил')),
            ],
            options={
                'verbose_name': 'аккаунт Pinterest',
                'verbose_name_plural': 'аккаунты Pinterest',
            },
        ),
    ]
