# Generated by Django 5.2.17 on 2026-09-28 05:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_alter_business_options_alter_business_archived_at_and_more'),
        ('pinterest', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pinterestaccount',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='дата отключения'),
        ),
        migrations.AlterField(
            model_name='pinterestaccount',
            name='pinterest_user_id',
            field=models.CharField(max_length=100, verbose_name='ID Pinterest'),
        ),
        migrations.AddConstraint(
            model_name='pinterestaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('pinterest_user_id',), name='unique_active_pinterest_user'),
        ),
    ]
