# Generated by Django 5.2.17 on 2026-09-25 08:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': 'участник рабочего пространства', 'verbose_name_plural': 'участники рабочих пространств'},
        ),
        migrations.AlterModelOptions(
            name='workspace',
            options={'verbose_name': 'рабочее пространство', 'verbose_name_plural': 'рабочие пространства'},
        ),
        migrations.AlterField(
            model_name='membership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='публичный идентификатор'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Владелец'), ('ADMIN', 'Администратор'), ('EDITOR', 'Редактор'), ('VIEWER', 'Наблюдатель')], max_length=16, verbose_name='роль'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='дата изменения'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='workspaces.workspace', verbose_name='рабочее пространство'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_workspaces', to=settings.AUTH_USER_MODEL, verbose_name='создатель'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='name',
            field=models.CharField(max_length=200, verbose_name='название рабочего пространства'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='публичный идентификатор'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='slug',
            field=models.SlugField(max_length=220, unique=True, verbose_name='слаг'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='дата изменения'),
        ),
    ]
