"""Build single-request CSS files from the editable source stylesheets."""

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CSS = ROOT / "static" / "css"

APP_SOURCES = (
    "tokens.css",
    "base.css",
    "components/buttons.css",
    "components/panels.css",
    "components/forms.css",
    "components/dialogs.css",
    "components/interface-scale.css",
    "components/workbench.css",
    "shell.css",
)
LANDING_SOURCES = ("components/interface-scale.css", "landing.css")


def build(output: str, sources: tuple[str, ...]) -> None:
    chunks = ["/* Generated by scripts/build_css_bundles.py. Edit source CSS files. */\n"]
    for source in sources:
        content = (CSS / source).read_text(encoding="utf-8")
        if "@import" in content:
            raise ValueError(f"Unexpected CSS import in {source}")
        chunks.append(f"\n/* {source} */\n{content.rstrip()}\n")
    path = CSS / output
    result = "".join(chunks)
    if not path.exists() or path.read_text(encoding="utf-8") != result:
        path.write_text(result, encoding="utf-8")


if __name__ == "__main__":
    build("app.css", APP_SOURCES)
    build("landing.bundle.css", LANDING_SOURCES)
